import Nav from '../Nav'
import Head from 'next/head'
import TransitionLayout from './TransitionLayout'

export default function Layout({ children }) {
    return <>

        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Nav />
        {children}


        <style global jsx>{`
            .content {
                opacity: 0;
                background-color: cornflowerblue;
                transition: 1s;
              }
              
              .fadeIn {
                opacity: 1;
              }              
      `}</style>
    </>
}